data:
  params:
    batch_size: 2000
    num_workers: 5
    train:
      params:
        size: 32
      target: ldm.data.cifar10.CIFAR10Train
    validation:
      params:
        size: 32
      target: ldm.data.cifar10.CIFAR10Val
    wrap: false
  target: main.DataModuleFromConfig
lightning:
  callbacks:
    image_logger:
      params:
        batch_frequency: 5000
        increase_log_steps: false
        max_images: 8
      target: main.ImageLogger
  trainer:
    benchmark: true
    max_epochs: 30
model:
  base_learning_rate: 1.0e-06
  params:
    ablation_blocks: 9
    attention_flag: spatial
    channels: 3
    ckpt_path:  'path\to\pretrained\ldm.ckpt'
    cond_stage_config:
      params:
        embed_dim: 512
        key: class_label
        n_classes: 1001
      target: ldm.modules.encoders.modules.ClassEmbedder
    cond_stage_key: class_label
    cond_stage_trainable: true
    conditioning_key: crossattn
    first_stage_config:
      params:
        ddconfig:
          attn_resolutions:
          - 16
          - 8
          ch: 128
          ch_mult:
          - 1
          - 2
          double_z: true
          dropout: 0.0
          in_channels: 3
          num_res_blocks: 2
          out_ch: 3
          resolution: 32
          z_channels: 3
        embed_dim: 3
        lossconfig:
          target: torch.nn.Identity
        monitor: val/rec_loss
      target: ldm.models.autoencoder.AutoencoderKL
    first_stage_key: image
    image_size: 16
    linear_end: 0.0155
    linear_start: 0.0015
    log_every_t: 200
    loss_type: l2
    monitor: val/loss_simple_ema
    num_timesteps_cond: 1
    scheduler_config:
      params:
        cycle_lengths:
        - 10000000000000
        f_max:
        - 1.0
        f_min:
        - 1.0
        f_start:
        - 1.0e-06
        warm_up_steps:
        - 10000
      target: ldm.lr_scheduler.LambdaLinearScheduler
    timesteps: 1000
    train_condition_only: true
    unet_config:
      params:
        attention_resolutions:
        - 1
        - 2
        - 4
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        context_dim: 512
        image_size: 16
        in_channels: 3
        model_channels: 128
        num_heads: 8
        num_res_blocks: 2
        out_channels: 3
        transformer_depth: 1
        use_spatial_transformer: true
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
  target: ldm.models.diffusion.ddpm.LatentDiffusion
